using Newtonsoft.Json;
using System;
using System.Text;
using UnityEngine.Playables;

namespace Client
{
    public struct BridgeEventMessage
    {
        public static BridgeEventMessage DeserializeJson(string json) => JsonConvert.DeserializeObject<BridgeEventMessage>(json, new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore
        });
        public string data { get; set; }
        public string eventKey { get; set; }
    }
    public struct CharacterMessage
    {
        public static CharacterMessage DeserializeJson(string json) => JsonConvert.DeserializeObject<CharacterMessage>(json, new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore
        });
        public MessageAnimationInfo messageAnimationInfo { get; set; }
        public int characterId { get; set; }
        public string audioBytes64 { get; set; }
        public PlayerState playerState { get; set; }

        public void Copy(CharacterMessage from)
        {
            messageAnimationInfo = from.messageAnimationInfo;
            characterId = from.characterId;
            audioBytes64 = from.audioBytes64;
            playerState = from.playerState;
        }
    }
    public struct MessageCameraInfo
    {
        public int characterId;
    }

    public enum PlayerState { 
        play, pause, stop
    }
}

/*
 
 double slashes - not comment, that part of base64 string:
 //NExAAROQnUAU8YAGRvJWJuLmXNzgRL3ve9379+yPImrv37+5c//REQAAEKoiIiIn7ufxAMW5/D+Ty4Pn/KAgCAYggCDvlAfP/8H3/8oCDv0h7LOnBipcsAnv4zWgh6//NExA4UeXIIAZhQAF1XllrZbx9yUelJqAIFBYsecxywvC0yV6zbqeOkIh5yI9PiHYnJ1J/Z1/uZLOSHJW77iYWMWbf4fAiCFX//pmD4PlwJUDaGI1zrSJMwaU7lPBYk//NExA8VSc6cAZlAAAgce/T/P0soty92zS2ifUrXMfu/FKUVE9Cx9+9lQiqUcWbMHPN6fY1mPMFLlh4whf//3QiribkFxKjkHTn7/R///+FXGhMqKIyoWBA2ggeiHgKD//NExAwUQeakAdQoAInlB1lJE2atf6///3ar0464q1KVzUexdVlB3Rbi6CQRcQDBQRER5zHIYytsz5MmVyGDhA0oa8nILfaqc5e31dbGPrcpS6aZSkPB3EeEKDX/KGxv//NExA4VSeaoAMBMmJV5mkw/3/n/zkx09AFD+7+LXXbdyu1xrNskd0soKWgdOARX3XbHv6Yrca6hZXq5dThofA61TTUzYYn0HhBDy2bZdWwYhLL0Ve4vEZ+CzMZ4loGQ//NExAsU6Yq0AMDSlGvuCsI7ks6JA5/uie7+7nuhcmiQ3NOZG2I9DaAo5uCkX7NJ3RlGIVNHOrev1oMWsgQOSXXJ2Pr7O7qxRYoKQ9pb0scz/6f/QKLepl3BJuWPoHzV//NExAoUmX68AMPSlDRJDsX4otlAjMZs8z+ya9Z/6wtezfH3i9Y8kNC82SAbI7GgoYVIRQYiqKFNIjZIkRPECcYbcc1nyt71on5+SBRY0FA2YmN+ZVX/I0gX9vksGvKW//NExAoSQXrEAHvSlODp1ADEGrjyI34pLrwHD+Gn4uH5/s31Y8Y+JR/b6yj/SyvUFBqlycCZLMFXXPWvd56qP/zagrsIKPpUNpxtq9iuD4/LA4XcwDAJEdQb6VtYkcf8//NExBQRcXLEAIPQlMDWeek36Td/RnkO3S4lZs6Xt+xtahhUwOS7EECUuIAjxUpWsd818rsIUT5sjbFnooQtx8DTFq35Cv1a4ZUavAox8wzFTedH8lLXMxUehmuWoo2U//NExCEROaLAAHvOlDvmiG2x2H+Y6MeSOUoLDzFBJykE6yL5vTmPy3LXl3W/Iy9bFP8DRMjPb0Opqgblc3AloVVwEupu53pqPgzEDPczxOFlggoKhc3HM1Zx3pLdZXvN//NExC8RQSLAAHvacFMxJ5gkVomFBzafPJxWAHlR5uhpZmv+ZN1ImY5XlWZVZ5AfSSyHBKNvl1o8gz2yGmwxlzy267CT6jO0aCVd3ldT73Fx/XFsTVzmXW7QZJZmtwLC//NExD0ScQ68AMYecNRQ/KsSESoAe5Yo/mbW7r/g6MjeN7m4u+7yVgYruDKm2pe017tbsBSfDjoyHOotEeAww8hDhKl51mqlLdbX2ep0anUlYugI8OO7uFYSW6QehNW0//NExEYRCQq0AMYacN2JA0x/fDE1eyeBoxCvsKcAegthLl5bDofq3R0yM5TLNYrUucnJgFSw+DkaSIfM8mSOiUJcsVJHhKzt8qdVeAiNP////+/6ZZWJMEIAI54gASk7//NExFQSUKaAANvYTIhONDDnKgQkAmpH4cAqTY+dg6tnKXtGcbZg7oalRYIQHFgBBFeCAYtAAJwwfCPIFK3zkuIECcgf+iv//7//f+iJRtfRk7ARkYu14kAmnPiIKJA1//NExF0SgNaAANsGcKBlmBpiC3WMGRSEDoSG3DmdAyhXG5hgcXqamYIu2mto3rPdhu6t7Q84m1h5K5phC0jXFCqwgDDKIgAgUMBcAY8SeDGrznmzrLtHJNcNzTDAoMG8//NExGYg6cKYANYSlEGTq98M/8J11z5dd4DoW/nKrWJQK8hk2DK300pxAsv2IKapptQ9JuT0YMIZQqRql1DONbsMNgYLLYYSocnGUMHeS1SNIcGcYYoIuxq6K6fbBFNm//NExDUcyY6sAMYYlE7rvxS3ptd5+jND6JOmXp1Z4bls1KJEDAxjddbrS1bRRQ5kHNKDzUJw+SJ3nnL1aB0DgubUspq////9nf311c7iAwli0QGY5SrsCWWm8zwNJm1A//NExBQXCZa8AH4MlMeTVjLht9LZW7bXrNmOS2Kw23ShhtQBcss3KJmW3aStKtXkmrIpHG0soDkHkkkQmkjr+P2asZ526mk2Z8n3k9DQq4f1f///9Sr9x4LL+6/a6bE2//NExAoUsWa8AMPQleBflD2KbKMc4RprOQnr4/yDl8T1EeZJ3p4uJilwISpG8/nrqZzgwcQt7i4gqEUduTZwgyGcmqmk2iot6viXi2GdiLInEkNuf/bVWXn9D9OwUVtP//NExAoUwWawAMPGlbo2uSwNPp4GQCpEyekoDCTw+zJNMkBShkDmBSl4LAQ4L0tq4US+4X1fUa2Y1rlcc89YbBxKhyICCqpwjX5msHoNMSA6NuxLhrK7NFlEF6QCxsNe//NExAoRgLKkAMveTTgs6hemkxPiUpQT4DM4jeJ00i2k1HIdR8GCGpLiwHMrpWV62xdYtuLXRKePDqnd/Oul86/Hg2v/fBs2Ws7prWDtGHZn5YJ1JAOc85MmqHI2wWmZ//NExBcRSQ6MANPQcFihlMM8CeC7miTotsQnK3dE1FhNQgzHjGdsjyLDKW12da1C8nQd/nk73IWRYTRVeBdBwi6Mhro5zR7hjROHzBBh4FHntsTuck1Ns6i79WnDEgLg//NExCQRwN6EAVpIALRjwPvXFTyaNFptTlcI5K6jCKBhFwERDpEGg87+3wbraG0pMTWDCu4xdPMJxzCk0CJQsVoUgIFT/MPCV+RSWwl3o7Lx9ghQvUmZgjR2CfpUm6fe//NExDAdeaJ4AZt4AOzSSCqqgzFVSuh6eMFMwqxWWtbQ3jympZNb1W1/Nbdd//619f/Gq2///+oNrW/+Y2RDcAm1DHf3Kt/TjCMO1vEMe4j4zEhPUxJMizYkBNVpLzGl//NExA0SgN5AAdhAAMc5AYrZmVLDLua9D1NnKnaZ071+GWUqlVKAYSgpBrTWSK2pq8NH/K1AsLKIgaf///1gq5YKqBpyf////+nBPyJOEd5tAsaQmYzi5MswYUMCFsFU//NExBYQkGoEAHpGKCB5agTLgoHXHg6GoRWcQYHD3BNwDEPvrWr5Yr8c9LC2hA64VL2NRSy5H9n6qnw5StEKOslrxiVwoKLIxvo1IsJKHTktn9ecO0Ohp5E6GhEBQERL//NExCYR6JHYAHmMTAlLFs8EhUFnz3LETr9sqWT0thV3aFJUiAiJ2SYgKwERb0VMQU1FMy45OS41VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExDEAAANIAAAAADk5LjVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExIQAAANIAAAAADk5LjVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADk5LjVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADk5LjVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADk5LjVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NExKwAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NExKwAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
*/